name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.7

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          cp env.sample .env
      - name: Run Tests
        run: |
          python manage.py test
